name: SkratchTek
favicon: null
layout_spectrum: 0.9993936587125063
typography_spectrum: 0.07392
title: 'SkratchTek | creative collective'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#121701'
    - '#386506'
    - '#9ebd00'
    - '#eb0b0b'
  brandStrength: 0.8379154393915087
  lightness: 0.475227655377239
  saturation: 0.4421888526994735
  rhythmicContrast: 0.7163454273249954
purpose: []
